matrix:
  include:
  - language: python
    sudo: true
    python:
      - 3.5
    install:
      - pip install coveralls
      - pip install coverage
      - pip install nose
    script:
      - nosetests nose_helloWorld.py --with-coverage
    notifications:
      slack: coms3009-noted:kjOHHQyiAOoWS08knpjn110C
    after_success:
      coveralls
    
  - language: node_js
    node_js:
       - 0.12
    script: node script.js
