language: python
sudo: false
python: 3.5
install:
  - pip install coveralls
  - pip install coverage
  - pip install nose
script: nosetests nose_temp_API.py nose_helloWorld.py --with-coverage
notifications:
  slack: coms3009-noted:kjOHHQyiAOoWS08knpjn110C
after_success:
  coveralls
