language: python
sudo: false
python:
  - 2.7
install:
  - pip install coveralls
  - pip install coverage
  - pip install nose
  - npm install
  - npm install --dev
script:
  - nosetests nose_helloWorld.py --with-coverage
  - node script.js
notifications:
  slack: coms3009-noted:kjOHHQyiAOoWS08knpjn110C
after_success:
  coveralls
