language: python
sudo: false
python:
  - 2.7
install:
  - pip install coveralls
  - pip install coverage
  - pip install nose
script:
  - nosetests nose_helloWorld.py --with-coverage
after_success:
  coveralls
