matrix:
  include:
  - language: python
    sudo: false
    python:
      - "3.5"
      - "3.3"
      - "2.7"
      - "2.6"
    script: 
      - python test.py
      - python setup.py nosetests --with-coverage --cover-package pypiview
      
    before_install:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
    # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
    install: 
      - pip install .
      - pip install nose coverage
      - pip install coveralls

    after_success: coveralls
    
  - language: node_js
    node_js:
       - 0.12
    script: node script.js
